### ISSUE TITLE
couldn't find file 'store/rdr' and show_zero_stock_products preference not defined

### ISSUE THREAD

**Issue by Adam0964** [spree-contrib/spree_rdr_theme#18]
I installed the theme using the following:

1 - Added gem 'spree_rdr_theme', :git => 'git://github.com/spree/spree_rdr_theme.git'
    to the gem file
2- Bundled

3- Issued the command:
    rails g spree_rdr_theme:install

And here is the output:
      append  app/assets/javascripts/store/all.js
      append  app/assets/javascripts/store/all.js
      insert  app/assets/stylesheets/store/all.css

When I refreshed, this is what I got:
      couldn't find file 'store/rdr'

I, then issued the command:
    rake assets:clean 

and restarted the server and refreshed the page, only this time, I got this error:

```
Showing /Users/adam0964/.rvm/gems/ruby-2.0.0-p0/bundler/gems/spree-  1c316edf2d91/frontend/app/views/spree/shared/_products.html.erb where line #18 raised:
```

show_zero_stock_products preference not defined
Extracted source (around line #18):
15: 
16: <div class="list" id="products" data-hook>
17: <% products.each do |product| %>
18:   <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
19:     <div class="product">
20:       <h2><%= link_to product.name, product_path(product) %></h2>
21:       <p class="image">

Any clue, anyone?

**Comment by JDutil** [comment]
This extension was deprecated awhile ago and does not work with versions of spree newer than 1.2.x as far as I know.  See  http://spreecommerce.com/blog/spree-fancy-theme

If you would like to get it up and running you will need to investigate the changes made between the last few spree versions since 1.2.x.

**Comment by Adam0964** [comment]
Thanks for the quick reply. 

I followed your suggestion and installed the new theme at the link indicated. However, I got another error, with this theme too:

couldn't find file 'jquery-ui'

  (in /Users/adam0964/.rvm/gems/ruby-2.0.0-p0/bundler/gems/spree_fancy-e152f31f0284/app/assets/javascripts/store/spree_fancy.js:3)
Extracted source (around line #11):

8: <%= stylesheet_link_tag 'store/all', :media => 'screen' %>
9: 
10: <%= stylesheet_link_tag 'store/print', :media => 'print' %><%= csrf_meta_tags %>
11: <%= javascript_include_tag 'store/all' %>
12: 

Any thoughts?

**Comment by JDutil** [comment]
Please file your bug report on the proper extensions github issues.
