### ISSUE TITLE
Can't install assets

### ISSUE THREAD

**Issue by scanferla** [spree-contrib/spree_rdr_theme#3]
Here is what happens when I `rails g spree_rdr_theme:install`

```
gus@ubuntu:~/sites/topazio$ rails g spree_rdr_theme:install
/home/gus/.rvm/gems/ruby-1.9.2-p290/gems/deface-0.6.1/lib/deface/override.rb:58:in `initialize': Invalid action (ArgumentError)
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree_rdr_theme-65b583ca6648/app/overrides/replace_new_wishlist_form.rb:1:in `new'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree_rdr_theme-65b583ca6648/app/overrides/replace_new_wishlist_form.rb:1:in `<top (required)>'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `block in load'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree_rdr_theme-65b583ca6648/lib/spree_rdr_theme.rb:9:in `block in activate'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree_rdr_theme-65b583ca6648/lib/spree_rdr_theme.rb:8:in `glob'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree_rdr_theme-65b583ca6648/lib/spree_rdr_theme.rb:8:in `activate'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:440:in `_run_prepare_callbacks'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/actionpack-3.1.0/lib/action_dispatch/middleware/reloader.rb:46:in `prepare!'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/application/finisher.rb:41:in `block in <module:Finisher>'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `instance_exec'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `run'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `each'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `run_initializers'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/application.rb:92:in `initialize!'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/gus/sites/topazio/config/environment.rb:5:in `<top (required)>'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `block in require'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/application.rb:78:in `require_environment!'
    from /home/gus/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.0/lib/rails/commands.rb:22:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Please let me know if you need any other info in order to help me.

Thanks in advance,
Gustavo

**Comment by lelesrc** [comment]
same here:

$ rails g spree_rdr_theme:install
/opt/spree-cas/spree/ruby/1.8/gems/deface-0.6.1/lib/deface/override.rb:58:in `initialize': Invalid action (ArgumentError)
        from /opt/spree-cas/vendor/git/spree_rdr_theme/lib/../app/overrides/replace_new_wishlist_form.rb:1:in`new'
        from /opt/spree-cas/vendor/git/spree_rdr_theme/lib/../app/overrides/replace_new_wishlist_form.rb:1
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in`load'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in`new_constants_in'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in`load'
        from /opt/spree-cas/vendor/git/spree_rdr_theme/lib/spree_rdr_theme.rb:9:in `activate'
        from /opt/spree-cas/vendor/git/spree_rdr_theme/lib/spree_rdr_theme.rb:8:in`glob'
        from /opt/spree-cas/vendor/git/spree_rdr_theme/lib/spree_rdr_theme.rb:8:in `activate'
        from /opt/spree-cas/vendor/git/spree_rdr_theme/lib/spree_rdr_theme.rb:15:in`_callback_before_33'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:440:in `_run_prepare_callbacks'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in`send'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /opt/spree-cas/spree/ruby/1.8/gems/actionpack-3.1.0/lib/action_dispatch/middleware/reloader.rb:46:in`prepare!'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/application/finisher.rb:41
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `instance_exec'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/initializable.rb:25:in`run'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/initializable.rb:50:in `run_initializers'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/initializable.rb:49:in`each'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `run_initializers'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/application.rb:92:in`initialize!'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `send'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in`method_missing'
        from /opt/spree-cas/config/environment.rb:5
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in`require'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in`new_constants_in'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
        from /opt/spree-cas/spree/ruby/1.8/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in`require'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/application.rb:78:in `require_environment!'
        from /opt/spree-cas/spree/ruby/1.8/gems/railties-3.1.0/lib/rails/commands.rb:22
        from script/rails:6:in`require'
        from script/rails:6

**Comment by bmalek** [comment]
I get the same error! is there a solution yet?

**Comment by bmalek** [comment]
The problem was in the '/home/bmalek/.bundler/ruby/1.8/spree_rdr_theme-050d729a767b/lib/../app/overrides/replace_new_wishlist_form.rb' which had assumed spree_wishlist is installed, add the following code to the file above and it should work

if Rails.application.railties.all.map(&:railtie_name).include? "spree_wishlist"
..........
end

**Comment by GeekOnCoffee** [comment]
This doesn't seem to be an issue anymore.
