### ISSUE TITLE
Checkout.js isn't precompiled

### ISSUE THREAD

**Issue by aew** [spree-contrib/spree_rdr_theme#6]
Hello - 

I'm trying to make the demo work with the RDR theme and I'm getting the following error:

 ActionView::Template::Error (checkout.js isn't precompiled):
    1: <% content_for :javascripts do %>
    2:   <%= javascript_include_tag 'checkout', '/states' %>
    3: <% end %>
    4:
    5: <div id="content" role="content">

I'm using a precompile step before deploying to Heroku.  All of the other assets seem to have precompiled successfully.  Is there a reason why Checkout.js, which is associated with RDR theme, would have been excluded?  Any idea on how to fix?

Thanks,

Adam

**Comment by radar** [comment]
What Heroku stack are you deploying to? Have you tried using the Cedar stack?

**Comment by aew** [comment]
Yes, Cedar Stack.  I was precompiling the assets locally before pushing to Heroku, and somehow the Checkout.js script from the theme was not finding it's way into the Vendor assets directory I suppose.  I am out of my depth.

**Comment by radar** [comment]
No worries :)

What happens if you add this line into the `Application` class?

``` ruby
config.assets.precompile += ['checkout.js']
```

Does that fix the issue?

**Comment by aew** [comment]
That fixed the issue.  Just don't ask me to explain it!  Thanks.

**Comment by radar** [comment]
Alright then, I'll leave this issue open as a reminder to update spree_rdr_theme to include this option automatically or another fix. Thanks!
